--- #YAML:1.0
name:               SVN-Hooks
version:            1.00
abstract:           A framework for implementing Subversion hooks.
author:
    - Gustavo Chaves <gnustavo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::Send:          0
    Email::Simple:        0
    Email::Simple::Creator:  0
    JIRA::Client:         0
    SVN::Look:            0
    SVN::Notify:          0
    Test::More:           0
    XMLRPC::Lite:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
