--- #YAML:1.0
name:                SVN-Hooks
version:             0.22
abstract:            A framework for implementing Subversion hooks.
license:             ~
author:              
    - Gustavo Chaves <gnustavo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Email::Send:                   0
    Email::Simple:                 0
    Email::Simple::Creator:        0
    JIRA::Client:                  0
    SVN::Look:                     0
    SVN::Notify:                   0
    Test::More:                    0
    XMLRPC::Lite:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
