---
abstract: 'Framework for implementing Subversion hooks'
author:
  - 'Gustavo L. de M. Chaves <gnustavo@cpan.org>'
build_requires:
  File::Copy: 0
  Test::More: 0
  URI::file: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Hooks
requires:
  Carp: 0
  Cwd: 0
  Data::Util: 0
  Exporter: 0
  File::Basename: 0
  File::Path: 0
  File::Spec::Functions: 0
  File::Temp: 0
  JIRA::Client: 0
  SVN::Look: 0
  SVN::Notify: 0
  XMLRPC::Lite: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gnustavo/SVN-Hooks/issues
  homepage: http://search.cpan.org/dist/SVN-Hooks/
  repository: git://github.com/gnustavo/SVN-Hooks.git
version: 1.27
